package com.muiezarif.livewallpaper.utils

object ApplicationConstants {
    const val DIGITAL_CLOCK_SIZE = "digitalClockSize_key"
    const val DIGITAL_CLOCK_SIZE1 = "digitalClockSize1_key"
    const val DIGITAL_COLOR_BACKGROUND="digitalColorBackGround_key"
    const val DIGITAL_COLOR_BACKGROUND1="digitalColorBackGround1_key"
    const val DIGITAL_CLOCK_STYLE="digitalClockStyle_key"
    const val DIGITAL_CLOCK_STYLE1="digitalClockStyle1_key"
    const val DIGITAL_CLOCK_COLOR="digitalClockColor_key"
    const val DIGITAL_CLOCK_COLOR1="digitalClockColor1_key"
    const val DIGITAL_CLOCK_POSITION_VERTICAL="digitalClockPositionVertical_key"
    const val DIGITAL_CLOCK_POSITION_VERTICAL1="digitalClockPositionVertical1_key"
    const val DIGITAL_CLOCK_POSITION_HORIZONTAL="digitalClockPositionHorizontal_key"
    const val DIGITAL_CLOCK_POSITION_HORIZONTAL1="digitalClockPositionHorizontal1_key"
    const val DIGITAL_CLOCK_DISPLAY_DATE_FORMAT="digitalClockDisplayDateFormat_key"
    const val DIGITAL_CLOCK_DISPLAY_DATE_FORMAT1="digitalClockDisplayDateFormat1_key"
    const val DIGITAL_CLOCK_24_HOUR_FORMAT="digitalClock24HourFormat_key"
    const val DIGITAL_CLOCK_SHOW_SECONDS="digitalClockShowSeconds_key"
    const val DIGITAL_CLOCK_SHOW_DATE="digitalClockShowDate_key"
    const val DIGITAL_CLOCK_DAY_OF_WEEK="digitalClockShowDayOfWeek_key"
    const val DIGITAL_CLOCK_SHOW_GLOW="digitalClockShowGlow_key"
    const val ANALOG_CLOCK_SIZE_OF_CLOCK="analogClockSize_key"
    const val ANALOG_CLOCK_SIZE_OF_CLOCK1="analogClockSize1_key"
    const val ANALOG_CLOCK_FONT="analogClockFont_key"
    const val ANALOG_CLOCK_FONT1="analogClockFont1_key"
    const val ANALOG_CLOCK_POSITION="analogClockPosition_key"
    const val ANALOG_CLOCK_POSITION1="analogClockPosition1_key"
    const val ANALOG_CLOCK_SHAPE="analogClockShape_key"
    const val ANALOG_CLOCK_SHAPE1="analogClockShape1_key"
    const val ANALOG_CLOCK_NUMBER_TYPE="analogClockNumberType_key"
    const val ANALOG_CLOCK_NUMBER_TYPE1="analogClockNumberType1_key"
    const val ANALOG_CLOCK_BACKGROUND="analogClockBackground_key"
    const val ANALOG_CLOCK_BACKGROUND1="analogClockBackground1_key"
    const val ANALOG_CLOCK_TEXT_COLOR="analogClockTextColor_key"
    const val ANALOG_CLOCK_TEXT_COLOR1="analogClockTextColor1_key"
    const val ANALOG_CLOCK_COLOR="analogClockColor_key"
    const val ANALOG_CLOCK_COLOR1="analogClockColor1_key"
    const val ANALOG_CLOCK_SEC_ARROW_COLOR="analogClockSecArrowColor_key"
    const val ANALOG_CLOCK_SEC_ARROW_COLOR1="analogClockSecArrowColor1_key"
    const val ANALOG_CLOCK_MIN_ARROW_COLOR="analogClockMinArrowColor_key"
    const val ANALOG_CLOCK_MIN_ARROW_COLOR1="analogClockMinArrowColor1_key"
    const val ANALOG_CLOCK_HOUR_ARROW_COLOR="analogClockHourArrowColor_key"
    const val ANALOG_CLOCK_HOUR_ARROW_COLOR1="analogClockHourArrowColor1_key"
    const val ANALOG_CLOCK_24_HOUR_FORMAT="analogClock24HourFormat_key"
    const val ANALOG_CLOCK_SHADOW_EFFECT="analogClockShadowEffect_key"
    const val ANALOG_CLOCK_SHOW_SEC_ARROW="analogClockShowSecArrow_key"
    const val ANALOG_CLOCK_SHOW_DATE="analogClockShowDate_key"
    const val ANALOG_CLOCK_SHOW_DAY="analogClockShowDay_key"
    const val ANALOG_CLOCK_SHOW_MONTH="analogClockShowMonth_key"
    const val ANALOG_CLOCK_SHOW_DIGITAL_CLOCK="analogClockShowDigitalClock_key"
    var checkColorBoxDigital: Int = 0
    var digitalClockSizeCheck = 8
    var clockPositionVerticalCheck = 100
    var clockPositionHorizontalCheck = 100
    var strDigital = 1
    var strFormat = "1"
    var strAnalog = 1
    var positionClockCheck = 1
    var shapeClockCheck = 0
    var numberTypeCheck = 0
    var analogClockSizeCheck = 8
    var checkColorBoxAnalog: Int = 0
}